import { promises as fs } from "node:fs";
import path from "node:path";

/**
 * Where the app remembers which folder the user picked. Lives next to the
 * source rather than in the vault itself, since we need it to find the vault.
 */
const CONFIG_FILE = path.join(process.cwd(), ".brainboard.json");

type Config = { dataPath: string | null };

async function readConfig(): Promise<Config> {
  try {
    const raw = await fs.readFile(CONFIG_FILE, "utf8");
    const parsed = JSON.parse(raw) as Partial<Config>;
    return { dataPath: typeof parsed.dataPath === "string" ? parsed.dataPath : null };
  } catch {
    return { dataPath: null };
  }
}

export async function getVaultPath(): Promise<string | null> {
  return (await readConfig()).dataPath;
}

/**
 * Resolve the vault, throwing if the user hasn't picked one yet. Every storage
 * operation goes through this so a missing vault fails loudly and early.
 */
export async function requireVaultPath(): Promise<string> {
  const dataPath = await getVaultPath();
  if (!dataPath) throw new VaultError("No data folder has been chosen yet.");
  return dataPath;
}

export class VaultError extends Error {}

/**
 * Point the app at `input`, creating the folder structure if needed. Returns
 * the absolute path actually used.
 */
export async function setVaultPath(input: string): Promise<string> {
  const trimmed = input.trim().replace(/^["']|["']$/g, "");
  if (!trimmed) throw new VaultError("Enter a folder path.");
  if (!path.isAbsolute(trimmed)) {
    throw new VaultError("Enter an absolute path, e.g. C:\\Users\\you\\brain-board-data");
  }

  const resolved = path.resolve(trimmed);

  // Refuse to treat an existing *file* as a vault; creating dirs under it fails
  // confusingly deeper in.
  try {
    const stat = await fs.stat(resolved);
    if (!stat.isDirectory()) throw new VaultError(`${resolved} is a file, not a folder.`);
  } catch (err) {
    if (err instanceof VaultError) throw err;
    // Doesn't exist yet - that's fine, we create it below.
  }

  try {
    await fs.mkdir(conceptsDir(resolved), { recursive: true });
    await fs.mkdir(filesDir(resolved), { recursive: true });
  } catch (err) {
    throw new VaultError(
      `Could not create the folder: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  await fs.writeFile(CONFIG_FILE, JSON.stringify({ dataPath: resolved }, null, 2), "utf8");
  return resolved;
}

export function conceptsDir(vault: string): string {
  return path.join(vault, "concepts");
}

export function filesDir(vault: string): string {
  return path.join(vault, "files");
}

/**
 * IDs are generated by us and only ever `[a-z0-9-]`. Enforcing that on the way
 * back in keeps a crafted id from walking out of the vault via `..`.
 */
export function assertSafeId(id: string): string {
  if (!/^[a-z0-9-]{1,64}$/.test(id)) throw new VaultError(`Invalid id: ${id}`);
  return id;
}

/**
 * Attachment names are user-supplied, so strip anything that could traverse or
 * confuse the filesystem while keeping the name recognizable.
 */
export function sanitizeFileName(name: string): string {
  const base = path.basename(name).replace(/[\u0000-\u001f<>:"/\|?*]/g, "_").trim();
  const cleaned = base.replace(/^\.+/, "").slice(0, 120);
  return cleaned || "file";
}

export function newId(): string {
  return (
    Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8)
  ).toLowerCase();
}
